/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.11.3.469 */
/* Module Version: 5.7 */
/* Sun Jul 14 22:23:22 2024 */

/* parameterized module instance */
RPLL __ (.CLKI( ), .CLKOP( ));
